
demo1:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus-1?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name:  com.mysql.jdbc.Driver

demo2:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus-2?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name:  com.mysql.jdbc.Driver

mybatis-plus:
  demo1:
    config-location: classpath:configs/myBatis-config.xml
    mapper-locations: classpath:mapper/model1/**/*.xml
    typeAliasesPackage: com.example.oldguy.modules.model1.dao.entities

  demo2:
    config-location: classpath:configs/myBatis-config.xml
    mapper-locations: classpath:mapper/model2/**/*.xml
    typeAliasesPackage: com.example.oldguy.modules.model2.dao.entities

logging:
  level:
    com.example.oldguy: debug